apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-namespace.yaml
- postgres-configmap.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- teleport-database.yaml